module Characters.All exposing (all)

import Characters.Monsters.GiantSpiders exposing (creviceDwellingGiantSpider)
import Characters.Monsters.Goblins exposing (..)
import Characters.Monsters.Orcs exposing (..)
import Characters.Monsters.Worgs exposing (boneGnawer)
import Characters.Rolodex
import Characters.TownFolk exposing (..)
import Types exposing (CharacterKey(..), Rolodex)


all : Rolodex
all =
    Characters.Rolodex.fromList
        [ ( Bobby, bobby )
        , ( Elmar, elmar )
        , ( Adabra, adabra )
        , ( Ander, ander )
        , ( Thistle, thistle )
        , ( Tablen, tablen )
        , ( Linene, linene )
        , ( Halia, halia )
        , ( Delilah, delilah )
        , ( Dazlyn, dazlyn )
        , ( Yarvun, yarvun )
        , ( Eliza, eliza )
        , ( Joanna, joanna )
        , ( Harbin, harbin )
        , ( Martha, martha )
        , ( John, john )
        , ( Norbus, norbus )
        , ( CreviceDwellingGiantSpider, creviceDwellingGiantSpider )
        , ( DeadGoblinKilledBySpiderInCrevice, deadGoblinKilledBySpiderInCrevice )
        , ( StargTheLeaping, stargTheLeaping )
        , ( DigrikTheAngry, digrikTheAngry )
        , ( StinkflankTheStinky, stinkflankTheStinky )
        , ( GrubGrubTheUnwholesome, grubGrubTheUnwholesome )
        , ( BearBelchTheBelcher, bearBelchTheBelcher )
        , ( RedEyeTheLazy, redEyeTheLazy )
        , ( WormFingersTheSlimy, wormFingersTheSlimy )
        , ( KrudrukTheThirsty, krudrukTheThirsty )
        , ( OculusTheRecordKeeper, oculusTheRecordKeeper )
        , ( GrabbeyTheDiaperWagger, grabbeyTheDiaperWagger )
        , ( CrankleTheCrotchety, crankleTheCrotchety )
        , ( NilgobTheTaskmaster, nilgobTheTaskmaster )
        , ( BoneGnawer, boneGnawer )
        , ( UltraGourmande, ultraGourmande )
        , ( Zoll, zoll )
        , ( Ghog, ghog )
        , ( Dhoman, dhoman )
        ]
